// Generated by scripts/generate-portfolio-data.mjs. Run: npm run portfolio:generate
export const portfolioCategories=[
  "All",
  "3D Logo Design",
  "Animated Logo Design",
  "Abstract Logo Design",
  "Mascot Logo Design",
  "Gaming Logo Design",
  "Clothing Logo Design",
  "Signature Logo Design",
  "Branding Design",
  "YouTube Channel Logo",
  "Website Development",
  "Mobile Development"
] as const;
export type PortfolioCategory=Exclude<(typeof portfolioCategories)[number],"All">;
export type PortfolioItem={id:number;title:string;category:PortfolioCategory;serviceSlug:string;image:string;alt:string;featured:boolean};
export const portfolioItems:PortfolioItem[]=[
  {
    "id": 1,
    "title": "3D Logo Design Project 1",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/1.jpg",
    "alt": "3D Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 2,
    "title": "3D Logo Design Project 2",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/2.jpg",
    "alt": "3D Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 3,
    "title": "3D Logo Design Project 3",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/3.jpg",
    "alt": "3D Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 4,
    "title": "3D Logo Design Project 4",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/4.jpg",
    "alt": "3D Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 5,
    "title": "3D Logo Design Project 5",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/5.jpg",
    "alt": "3D Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 6,
    "title": "3D Logo Design Project 6",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/6.jpg",
    "alt": "3D Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 7,
    "title": "3D Logo Design Project 7",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/7.jpg",
    "alt": "3D Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 8,
    "title": "3D Logo Design Project 8",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/8.jpg",
    "alt": "3D Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 9,
    "title": "3D Logo Design Project 9",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/9.jpg",
    "alt": "3D Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 10,
    "title": "3D Logo Design Project 10",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/10.jpg",
    "alt": "3D Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 11,
    "title": "3D Logo Design Project 11",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/11.jpg",
    "alt": "3D Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 12,
    "title": "3D Logo Design Project 12",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/12.jpg",
    "alt": "3D Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 13,
    "title": "3D Logo Design Project 13",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/13.jpg",
    "alt": "3D Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 14,
    "title": "3D Logo Design Project 14",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/14.jpg",
    "alt": "3D Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 15,
    "title": "3D Logo Design Project 15",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/15.jpg",
    "alt": "3D Logo Design portfolio project 15",
    "featured": false
  },
  {
    "id": 16,
    "title": "3D Logo Design Project 16",
    "category": "3D Logo Design",
    "serviceSlug": "3d-logo-design",
    "image": "/assets/portfolio/3D/16.jpg",
    "alt": "3D Logo Design portfolio project 16",
    "featured": false
  },
  {
    "id": 17,
    "title": "Abstract Logo Design Project 1",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/1.jpg",
    "alt": "Abstract Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 18,
    "title": "Abstract Logo Design Project 2",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/2.jpg",
    "alt": "Abstract Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 19,
    "title": "Abstract Logo Design Project 3",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/3.jpg",
    "alt": "Abstract Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 20,
    "title": "Abstract Logo Design Project 4",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/4.jpg",
    "alt": "Abstract Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 21,
    "title": "Abstract Logo Design Project 5",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/5.jpg",
    "alt": "Abstract Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 22,
    "title": "Abstract Logo Design Project 6",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/6.jpg",
    "alt": "Abstract Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 23,
    "title": "Abstract Logo Design Project 7",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/7.jpg",
    "alt": "Abstract Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 24,
    "title": "Abstract Logo Design Project 8",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/8.jpg",
    "alt": "Abstract Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 25,
    "title": "Abstract Logo Design Project 9",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/9.jpg",
    "alt": "Abstract Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 26,
    "title": "Abstract Logo Design Project 10",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/10.jpg",
    "alt": "Abstract Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 27,
    "title": "Abstract Logo Design Project 11",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/11.jpg",
    "alt": "Abstract Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 28,
    "title": "Abstract Logo Design Project 12",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/12.jpg",
    "alt": "Abstract Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 29,
    "title": "Abstract Logo Design Project 13",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/13.jpg",
    "alt": "Abstract Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 30,
    "title": "Abstract Logo Design Project 14",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/14.jpg",
    "alt": "Abstract Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 31,
    "title": "Abstract Logo Design Project 15",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/15.jpg",
    "alt": "Abstract Logo Design portfolio project 15",
    "featured": false
  },
  {
    "id": 32,
    "title": "Abstract Logo Design Project 16",
    "category": "Abstract Logo Design",
    "serviceSlug": "abstract-logo-design",
    "image": "/assets/portfolio/abstract/16.jpg",
    "alt": "Abstract Logo Design portfolio project 16",
    "featured": false
  },
  {
    "id": 33,
    "title": "Animated Logo Design Project 1",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-1.gif",
    "alt": "Animated Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 34,
    "title": "Animated Logo Design Project 2",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-2.gif",
    "alt": "Animated Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 35,
    "title": "Animated Logo Design Project 3",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-3.gif",
    "alt": "Animated Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 36,
    "title": "Animated Logo Design Project 4",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-4.gif",
    "alt": "Animated Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 37,
    "title": "Animated Logo Design Project 5",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-5.gif",
    "alt": "Animated Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 38,
    "title": "Animated Logo Design Project 6",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-6.gif",
    "alt": "Animated Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 39,
    "title": "Animated Logo Design Project 7",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-7.gif",
    "alt": "Animated Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 40,
    "title": "Animated Logo Design Project 8",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-8.gif",
    "alt": "Animated Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 41,
    "title": "Animated Logo Design Project 9",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-9.gif",
    "alt": "Animated Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 42,
    "title": "Animated Logo Design Project 10",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-10.gif",
    "alt": "Animated Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 43,
    "title": "Animated Logo Design Project 11",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-11.gif",
    "alt": "Animated Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 44,
    "title": "Animated Logo Design Project 12",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-12.gif",
    "alt": "Animated Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 45,
    "title": "Animated Logo Design Project 13",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-13.gif",
    "alt": "Animated Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 46,
    "title": "Animated Logo Design Project 14",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-14.gif",
    "alt": "Animated Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 47,
    "title": "Animated Logo Design Project 15",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-15.gif",
    "alt": "Animated Logo Design portfolio project 15",
    "featured": false
  },
  {
    "id": 48,
    "title": "Animated Logo Design Project 16",
    "category": "Animated Logo Design",
    "serviceSlug": "animated-logo-design",
    "image": "/assets/portfolio/animated/logo-16.gif",
    "alt": "Animated Logo Design portfolio project 16",
    "featured": false
  },
  {
    "id": 49,
    "title": "Branding Design Project 1",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/1.jpg",
    "alt": "Branding Design portfolio project 1",
    "featured": true
  },
  {
    "id": 50,
    "title": "Branding Design Project 2",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/2.jpg",
    "alt": "Branding Design portfolio project 2",
    "featured": false
  },
  {
    "id": 51,
    "title": "Branding Design Project 3",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/3.jpg",
    "alt": "Branding Design portfolio project 3",
    "featured": false
  },
  {
    "id": 52,
    "title": "Branding Design Project 4",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/4.jpg",
    "alt": "Branding Design portfolio project 4",
    "featured": false
  },
  {
    "id": 53,
    "title": "Branding Design Project 5",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/5.jpg",
    "alt": "Branding Design portfolio project 5",
    "featured": false
  },
  {
    "id": 54,
    "title": "Branding Design Project 6",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/6.jpg",
    "alt": "Branding Design portfolio project 6",
    "featured": false
  },
  {
    "id": 55,
    "title": "Branding Design Project 7",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/7.jpg",
    "alt": "Branding Design portfolio project 7",
    "featured": false
  },
  {
    "id": 56,
    "title": "Branding Design Project 8",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/8.jpg",
    "alt": "Branding Design portfolio project 8",
    "featured": false
  },
  {
    "id": 57,
    "title": "Branding Design Project 9",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/9.jpg",
    "alt": "Branding Design portfolio project 9",
    "featured": false
  },
  {
    "id": 58,
    "title": "Branding Design Project 10",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/10.jpg",
    "alt": "Branding Design portfolio project 10",
    "featured": false
  },
  {
    "id": 59,
    "title": "Branding Design Project 11",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/11.jpg",
    "alt": "Branding Design portfolio project 11",
    "featured": false
  },
  {
    "id": 60,
    "title": "Branding Design Project 12",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/12.jpg",
    "alt": "Branding Design portfolio project 12",
    "featured": false
  },
  {
    "id": 61,
    "title": "Branding Design Project 13",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/13.jpg",
    "alt": "Branding Design portfolio project 13",
    "featured": false
  },
  {
    "id": 62,
    "title": "Branding Design Project 14",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/14.jpg",
    "alt": "Branding Design portfolio project 14",
    "featured": false
  },
  {
    "id": 63,
    "title": "Branding Design Project 15",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/15.jpg",
    "alt": "Branding Design portfolio project 15",
    "featured": false
  },
  {
    "id": 64,
    "title": "Branding Design Project 16",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/16.jpg",
    "alt": "Branding Design portfolio project 16",
    "featured": false
  },
  {
    "id": 65,
    "title": "Branding Design Project 17",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/17.jpg",
    "alt": "Branding Design portfolio project 17",
    "featured": false
  },
  {
    "id": 66,
    "title": "Branding Design Project 18",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/18.jpg",
    "alt": "Branding Design portfolio project 18",
    "featured": false
  },
  {
    "id": 67,
    "title": "Branding Design Project 19",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/19.jpg",
    "alt": "Branding Design portfolio project 19",
    "featured": false
  },
  {
    "id": 68,
    "title": "Branding Design Project 20",
    "category": "Branding Design",
    "serviceSlug": "branding-design",
    "image": "/assets/portfolio/Branding/20.jpg",
    "alt": "Branding Design portfolio project 20",
    "featured": false
  },
  {
    "id": 69,
    "title": "Clothing Logo Design Project 1",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/1.jpg",
    "alt": "Clothing Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 70,
    "title": "Clothing Logo Design Project 2",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/2.jpg",
    "alt": "Clothing Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 71,
    "title": "Clothing Logo Design Project 3",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/3.jpg",
    "alt": "Clothing Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 72,
    "title": "Clothing Logo Design Project 4",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/4.jpg",
    "alt": "Clothing Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 73,
    "title": "Clothing Logo Design Project 5",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/5.jpg",
    "alt": "Clothing Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 74,
    "title": "Clothing Logo Design Project 6",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/6.jpg",
    "alt": "Clothing Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 75,
    "title": "Clothing Logo Design Project 7",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/7.jpg",
    "alt": "Clothing Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 76,
    "title": "Clothing Logo Design Project 8",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/8.jpg",
    "alt": "Clothing Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 77,
    "title": "Clothing Logo Design Project 9",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/9.jpg",
    "alt": "Clothing Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 78,
    "title": "Clothing Logo Design Project 10",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/10.jpg",
    "alt": "Clothing Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 79,
    "title": "Clothing Logo Design Project 11",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/11.jpg",
    "alt": "Clothing Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 80,
    "title": "Clothing Logo Design Project 12",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/12.jpg",
    "alt": "Clothing Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 81,
    "title": "Clothing Logo Design Project 13",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/13.jpg",
    "alt": "Clothing Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 82,
    "title": "Clothing Logo Design Project 14",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/14.jpg",
    "alt": "Clothing Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 83,
    "title": "Clothing Logo Design Project 15",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/16.jpg",
    "alt": "Clothing Logo Design portfolio project 15",
    "featured": false
  },
  {
    "id": 84,
    "title": "Clothing Logo Design Project 16",
    "category": "Clothing Logo Design",
    "serviceSlug": "clothing-logo-design",
    "image": "/assets/portfolio/Clothing/17.jpg",
    "alt": "Clothing Logo Design portfolio project 16",
    "featured": false
  },
  {
    "id": 85,
    "title": "Gaming Logo Design Project 1",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/1.jpg",
    "alt": "Gaming Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 86,
    "title": "Gaming Logo Design Project 2",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/2.jpg",
    "alt": "Gaming Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 87,
    "title": "Gaming Logo Design Project 3",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/3.jpg",
    "alt": "Gaming Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 88,
    "title": "Gaming Logo Design Project 4",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/4.jpg",
    "alt": "Gaming Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 89,
    "title": "Gaming Logo Design Project 5",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/5.jpg",
    "alt": "Gaming Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 90,
    "title": "Gaming Logo Design Project 6",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/6.jpg",
    "alt": "Gaming Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 91,
    "title": "Gaming Logo Design Project 7",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/7.jpg",
    "alt": "Gaming Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 92,
    "title": "Gaming Logo Design Project 8",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/8.jpg",
    "alt": "Gaming Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 93,
    "title": "Gaming Logo Design Project 9",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/9.jpg",
    "alt": "Gaming Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 94,
    "title": "Gaming Logo Design Project 10",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/10.jpg",
    "alt": "Gaming Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 95,
    "title": "Gaming Logo Design Project 11",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/11.jpg",
    "alt": "Gaming Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 96,
    "title": "Gaming Logo Design Project 12",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/12.jpg",
    "alt": "Gaming Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 97,
    "title": "Gaming Logo Design Project 13",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/13.jpg",
    "alt": "Gaming Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 98,
    "title": "Gaming Logo Design Project 14",
    "category": "Gaming Logo Design",
    "serviceSlug": "gaming-logo-design",
    "image": "/assets/portfolio/Gaming/16.jpg",
    "alt": "Gaming Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 99,
    "title": "Mascot Logo Design Project 1",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/1.jpg",
    "alt": "Mascot Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 100,
    "title": "Mascot Logo Design Project 2",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/2.jpg",
    "alt": "Mascot Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 101,
    "title": "Mascot Logo Design Project 3",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/3-1.jpg",
    "alt": "Mascot Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 102,
    "title": "Mascot Logo Design Project 4",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/3.jpg",
    "alt": "Mascot Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 103,
    "title": "Mascot Logo Design Project 5",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/4.jpg",
    "alt": "Mascot Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 104,
    "title": "Mascot Logo Design Project 6",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/5.jpg",
    "alt": "Mascot Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 105,
    "title": "Mascot Logo Design Project 7",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/6-3.jpg",
    "alt": "Mascot Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 106,
    "title": "Mascot Logo Design Project 8",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/6.jpg",
    "alt": "Mascot Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 107,
    "title": "Mascot Logo Design Project 9",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/7.jpg",
    "alt": "Mascot Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 108,
    "title": "Mascot Logo Design Project 10",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/8.jpg",
    "alt": "Mascot Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 109,
    "title": "Mascot Logo Design Project 11",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/9.jpg",
    "alt": "Mascot Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 110,
    "title": "Mascot Logo Design Project 12",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/10.jpg",
    "alt": "Mascot Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 111,
    "title": "Mascot Logo Design Project 13",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/11.jpg",
    "alt": "Mascot Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 112,
    "title": "Mascot Logo Design Project 14",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/12.jpg",
    "alt": "Mascot Logo Design portfolio project 14",
    "featured": false
  },
  {
    "id": 113,
    "title": "Mascot Logo Design Project 15",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/14.jpg",
    "alt": "Mascot Logo Design portfolio project 15",
    "featured": false
  },
  {
    "id": 114,
    "title": "Mascot Logo Design Project 16",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/15.jpg",
    "alt": "Mascot Logo Design portfolio project 16",
    "featured": false
  },
  {
    "id": 115,
    "title": "Mascot Logo Design Project 17",
    "category": "Mascot Logo Design",
    "serviceSlug": "mascot-logo-design",
    "image": "/assets/portfolio/Mascot/16.jpg",
    "alt": "Mascot Logo Design portfolio project 17",
    "featured": false
  },
  {
    "id": 116,
    "title": "Signature Logo Design Project 1",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/1.jpg",
    "alt": "Signature Logo Design portfolio project 1",
    "featured": true
  },
  {
    "id": 117,
    "title": "Signature Logo Design Project 2",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/2.jpg",
    "alt": "Signature Logo Design portfolio project 2",
    "featured": false
  },
  {
    "id": 118,
    "title": "Signature Logo Design Project 3",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/3.jpg",
    "alt": "Signature Logo Design portfolio project 3",
    "featured": false
  },
  {
    "id": 119,
    "title": "Signature Logo Design Project 4",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/4.jpg",
    "alt": "Signature Logo Design portfolio project 4",
    "featured": false
  },
  {
    "id": 120,
    "title": "Signature Logo Design Project 5",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/5.jpg",
    "alt": "Signature Logo Design portfolio project 5",
    "featured": false
  },
  {
    "id": 121,
    "title": "Signature Logo Design Project 6",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/6.jpg",
    "alt": "Signature Logo Design portfolio project 6",
    "featured": false
  },
  {
    "id": 122,
    "title": "Signature Logo Design Project 7",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/7.jpg",
    "alt": "Signature Logo Design portfolio project 7",
    "featured": false
  },
  {
    "id": 123,
    "title": "Signature Logo Design Project 8",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/8.jpg",
    "alt": "Signature Logo Design portfolio project 8",
    "featured": false
  },
  {
    "id": 124,
    "title": "Signature Logo Design Project 9",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/9.jpg",
    "alt": "Signature Logo Design portfolio project 9",
    "featured": false
  },
  {
    "id": 125,
    "title": "Signature Logo Design Project 10",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/10.jpg",
    "alt": "Signature Logo Design portfolio project 10",
    "featured": false
  },
  {
    "id": 126,
    "title": "Signature Logo Design Project 11",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/11.jpg",
    "alt": "Signature Logo Design portfolio project 11",
    "featured": false
  },
  {
    "id": 127,
    "title": "Signature Logo Design Project 12",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/12.jpg",
    "alt": "Signature Logo Design portfolio project 12",
    "featured": false
  },
  {
    "id": 128,
    "title": "Signature Logo Design Project 13",
    "category": "Signature Logo Design",
    "serviceSlug": "signature-logo-design",
    "image": "/assets/portfolio/Signature/image 4.png",
    "alt": "Signature Logo Design portfolio project 13",
    "featured": false
  },
  {
    "id": 129,
    "title": "YouTube Channel Logo Project 1",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/1.jpg",
    "alt": "YouTube Channel Logo portfolio project 1",
    "featured": true
  },
  {
    "id": 130,
    "title": "YouTube Channel Logo Project 2",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/2.jpg",
    "alt": "YouTube Channel Logo portfolio project 2",
    "featured": false
  },
  {
    "id": 131,
    "title": "YouTube Channel Logo Project 3",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/3.jpg",
    "alt": "YouTube Channel Logo portfolio project 3",
    "featured": false
  },
  {
    "id": 132,
    "title": "YouTube Channel Logo Project 4",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/4.jpg",
    "alt": "YouTube Channel Logo portfolio project 4",
    "featured": false
  },
  {
    "id": 133,
    "title": "YouTube Channel Logo Project 5",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/5.jpg",
    "alt": "YouTube Channel Logo portfolio project 5",
    "featured": false
  },
  {
    "id": 134,
    "title": "YouTube Channel Logo Project 6",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/6.jpg",
    "alt": "YouTube Channel Logo portfolio project 6",
    "featured": false
  },
  {
    "id": 135,
    "title": "YouTube Channel Logo Project 7",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/7.jpg",
    "alt": "YouTube Channel Logo portfolio project 7",
    "featured": false
  },
  {
    "id": 136,
    "title": "YouTube Channel Logo Project 8",
    "category": "YouTube Channel Logo",
    "serviceSlug": "youtube-channel-logo",
    "image": "/assets/portfolio/Youtube/8.jpg",
    "alt": "YouTube Channel Logo portfolio project 8",
    "featured": false
  }
];
